#include "kcpch.h"
#include "World/Block.h"

namespace KuchCraft {

	bool Block::IsTransparent(const Block& block)
	{
		switch (block.Type)
		{
			case BlockType::Air:    return true;
			case BlockType::Water:  return true;
			case BlockType::Ice:    return true;
			case BlockType::Glass:  return true;
		}
		return false;
	}

	bool Block::IsSolid(const Block& block)
	{
		switch (block.Type)
		{
			case BlockType::Air:    return false;
			case BlockType::Water:  return false;
		}
		return true;
	}

	const std::string& Block::GetName(const Block& block)
	{
		return s_BlockNames[block];
	}

	std::unordered_map<BlockType, std::string> Block::s_BlockNames = {
		{ BlockType::Air,                             "air"                                 },
		{ BlockType::AcaciaLog,                       "acacia log"                          },
		{ BlockType::AcaciaPlanks,                    "acacia planks"                       },
		{ BlockType::Amethyst,                        "amethyst"                            },
		{ BlockType::AncientDebris,                   "ancient debris"                      },
		{ BlockType::Andesite,                        "andesite"                            },
		{ BlockType::Bedrock,                         "bedrock"                             },
		{ BlockType::Bricks,                          "bricks"                              },
		{ BlockType::Bambo,                           "bambo"                               },
		{ BlockType::BamboPlanks,                     "bambo planks"                        },
		{ BlockType::BamboMosaic,                     "bambo mosaic"                        },
		{ BlockType::Barrel,                          "barrel"                              },
		{ BlockType::Basalt,                          "basalt"                              },
		{ BlockType::BeeNest,                         "bee nest"                            },
		{ BlockType::BeeHive,                         "beehive"                             },
		{ BlockType::BirchLog,                        "birch log"                           },
		{ BlockType::BirchPlanks,                     "birch planks"                        },
		{ BlockType::BlackConcrete,                   "black concrete"                      },
		{ BlockType::BlackConcretePowder,             "black concrete powder"               },
		{ BlockType::BlackWool,                       "black wool"                          },
		{ BlockType::BlackStone,                      "black stone"                         },
		{ BlockType::BlastFurnace,                    "blast furnace"                       },
		{ BlockType::BlueConcrete,                    "blue concrete"                       },
		{ BlockType::BlueConcretePowder,              "blue concrete powder"                },
		{ BlockType::BlueIce,                         "blue ice"                            },
		{ BlockType::BlueWool,                        "blue wool"                           },
		{ BlockType::Bone,                            "bone"                                },
		{ BlockType::BookShelf,                       "book shelf"                          },
		{ BlockType::BrainCoral,                      "brain coral"                         },
		{ BlockType::BrownConcrete,                   "brown concrete"                      },
		{ BlockType::BrownConcretePowder,             "brown concrete powder"               },
		{ BlockType::CoalOre,                         "coal ore"                            },
		{ BlockType::CarvedPumpkin,                   "carved pumpkin"                      },
		{ BlockType::Cobblestone,                     "cobblestone"                         },
		{ BlockType::CraftingTable,                   "crafting table"                      },
		{ BlockType::CherryLog,                       "cherry log"                          },
		{ BlockType::CherryPlanks,                    "cherry planks"                       },
		{ BlockType::ChiseledCopper,                  "chiseled copper"                     },
		{ BlockType::ChiseledDeepslate,               "chiseled deepslate"                  },
		{ BlockType::ChiseledNetherBricks,            "chiseled nether bricks"              },
		{ BlockType::ChiseledPolishedBlackstone,      "chiseled polished blackstone"        },
		{ BlockType::ChiseledQuartz,                  "chiseled quartz"                     },
		{ BlockType::ChiseledRedSandstone,            "chiseled red sandstone"              },
		{ BlockType::ChiseledSandstone,               "chiseled sandstone"                  },
		{ BlockType::ChiseledStoneBricks,             "chiseled stone bricks"               },
		{ BlockType::ChiseledTuff,                    "chiseled tuff"                       },
		{ BlockType::ChiseledTuffBricks,              "chiseled tuff bricks"                },
		{ BlockType::Clay,                            "clay"                                },
		{ BlockType::Coal,                            "coal"                                },
		{ BlockType::CorseDirt,                       "corse dirt"                          },
		{ BlockType::CobbledDeepslate,                "cobbled deepslate"                   },
		{ BlockType::Copper,                          "copper"                              },
		{ BlockType::CopperOre,                       "copper ore"                          },
		{ BlockType::CrackedDeepslateBricks,          "cracked deepslate bricks"            },
		{ BlockType::CrackedDeepslateTiles,           "cracked deepslate tiles"             },
		{ BlockType::CrackedNetherBricks,             "cracked nether bricks"               },
		{ BlockType::CrackedPolishedBlackstoneBricks, "cracked polished blackstone bricks"  },
		{ BlockType::CrackedStoneBricks,              "cracked stone bricks"                },
		{ BlockType::CrimsonLog,                      "crimson log"                         },
		{ BlockType::CrimsonPlanks,                   "crimson planks"                      },
		{ BlockType::CrimsonLogStriped,               "crimson log striped"                 },
		{ BlockType::CryingObsidian,                  "crying obsidian"                     },
		{ BlockType::CutCopper,                       "cut copper"                          },
		{ BlockType::CyanConcrete,                    "cyan concrete"                       },
		{ BlockType::CyanConcretePowder,              "cyan concrete powder"                },
		{ BlockType::CyanWool,                        "cyan wool"                           },
		{ BlockType::DarkOakLog,                      "dark oak log"                        },
		{ BlockType::DarkOakPlanks,                   "dark oak planks"                     },
		{ BlockType::DarkPrismarine,                  "dark prismarine"                     },
		{ BlockType::Deepslate,                       "deepslate"                           },
		{ BlockType::DeepslateBricks,                 "deepslate bricks"                    },
		{ BlockType::DeepslateCoalOre,                "deepslate coal ore"                  },
		{ BlockType::DeepslateIronOre,                "deepslate iron ore"                  },
		{ BlockType::DeepslateCopperOre,              "deepslate copper ore"                },
		{ BlockType::DeepslateDiamondOre,             "deepslate diamond ore"               },
		{ BlockType::DeepslateEmeraldOre,             "deepslate emerald ore"               },
		{ BlockType::DeepslateGoldOre,                "deepslate gold ore"                  },
		{ BlockType::DeepslateLapisOre,               "deepslate lapis ore"                 },
		{ BlockType::DeepslateTiles,                  "deepslate tiles"                     },
		{ BlockType::Diamond,                         "diamond"                             },
		{ BlockType::DirtPath,                        "dirt path"                           },
		{ BlockType::Dripstone,                       "dripstone"                           },																			        
		{ BlockType::DiamondOre,                      "diamond ore"                         },
		{ BlockType::Dioryte,                         "dioryte"                             },
		{ BlockType::Dirt,                            "dirt"                                },
		{ BlockType::EmerladOre,                      "emerald ore"                         },
		{ BlockType::Emerald,                         "emerald"                             },
		{ BlockType::EndStone,                        "end stone"                           },
		{ BlockType::EndStoneBrick,                   "end stone brick"                     },
		{ BlockType::Furnace,                         "furnace"                             },
		{ BlockType::Furnace,                         "furnace"                             },
		{ BlockType::Farmland,                        "farmland"                            },
		{ BlockType::FireCoral,                       "fire coral"                          },
		{ BlockType::Granite,                         "granite"                             },
		{ BlockType::Grass,                           "grass"                               },
		{ BlockType::Gravel,                          "gravel"                              },
		{ BlockType::GildedBlackstone,                "gilded blackstone"                   },
		{ BlockType::Glass,                           "glass"                               },
		{ BlockType::Glowstone,                       "glowstone"                           },
		{ BlockType::Gold,                            "gold"                                },
		{ BlockType::GoldOre,                         "gold ore"                            },
		{ BlockType::GrassSnow,                       "grass snow"                          },
		{ BlockType::GreyConcrete,                    "grey concrete"                       },
		{ BlockType::GreyConcretePowder,              "grey concrete powder"                },
		{ BlockType::GreyWool,                        "grey wool"                           },
		{ BlockType::GreenConcrete,                   "green concrete"                      },
		{ BlockType::GreenConcretePowder,             "green concrete powder"               },
		{ BlockType::GreenWool,                       "green wool"                          },
		{ BlockType::Hay,                             "hay"                                 },
		{ BlockType::Ice,                             "ice"                                 },
		{ BlockType::Iron,                            "iron"                                },
		{ BlockType::IronOre,                         "iron ore"                            },
		{ BlockType::JungleLog,                       "jungle log"                          },
		{ BlockType::JunglePlanks,                    "jungle planks"                       },
		{ BlockType::Leaves,                          "leaves"                              },
		{ BlockType::Lapis,                           "lapis"                               },
		{ BlockType::LapisOre,                        "lapis ore"                           },
		{ BlockType::LightBlueConcrete,               "light blue concrete"                 },
		{ BlockType::LightBlueConcretePowder,         "light blue concrete powder"          },
		{ BlockType::LightBlueWool,                   "light blue wool"                     },
		{ BlockType::LightGreyConcrete,               "light grey concrete"                 },
		{ BlockType::LightGreyConcretePowder,         "light grey concrete powder"          },
		{ BlockType::LightGreyWool,                   "light grey wool"                     },
		{ BlockType::LimeConcrete,                    "lime concrete"                       },
		{ BlockType::LimeConcretePowder,              "lime concrete powder"                },
		{ BlockType::LimeWool,                        "lime wool"                           },
		{ BlockType::Lamp,                            "lamp"                                },
		{ BlockType::MagentaConcrete,                 "magenta concrete"                    },
		{ BlockType::MagentaConcretePowder,           "magenta concrete powder"             },
		{ BlockType::MagentaWool,                     "magenta wool"                        },
		{ BlockType::Melon,                           "melon"                               },
		{ BlockType::Mud,                             "mud"                                 },
		{ BlockType::MudBricks,                       "mud bricks"                          },
		{ BlockType::NetherBricks,                    "nether bricks"                       },
		{ BlockType::Netherrack,                      "netherrack"                          },
		{ BlockType::OrangeConcrete,                  "orange concrete"                     },
		{ BlockType::OrangeConcretePowder,            "orange concrete powder"              },
		{ BlockType::OrangeWool,                      "orange wool"                         },
		{ BlockType::OakLog,                          "oak log"                             },
		{ BlockType::OakPlanks,                       "oak planks"                          },
		{ BlockType::Pumpkin,                         "pumpkin"                             },
		{ BlockType::PinkConcrete,                    "pink concrete"                       },
		{ BlockType::PinkConcretePowder,              "pink concrete powder"                },
		{ BlockType::PinkWool,                        "pink wool"                           },
		{ BlockType::PolishedAndesite,                "polished andesite"                   },
		{ BlockType::PolishedBasalt,                  "polished basalt"                     },
		{ BlockType::PrismarineBricks,                "prismarine bricks"                   },
		{ BlockType::PurpleConcrete,                  "purple concrete"                     },
		{ BlockType::PurpleConcretePowder,            "purple concrete powder"              },
		{ BlockType::PurpleWool,                      "purple wool"                         },
		{ BlockType::PurpurPillar,                    "purpur pillar"                       },
		{ BlockType::Quartz,                          "quartz"                              },
		{ BlockType::QuartzBricks,                    "quartz bricks"                       },
		{ BlockType::QuartzPillar,                    "quartz pillar"                       },
		{ BlockType::RedConcrete,                     "red concrete"                        },
		{ BlockType::RedConcretePowder,               "red concrete powder"                 },
		{ BlockType::RedWool,                         "red wool"                            },
		{ BlockType::Sand,                            "sand"                                },
		{ BlockType::SoulSand,                        "soul sand"                           },
		{ BlockType::Sandstone,                       "sandstone"                           },
		{ BlockType::Snow,                            "snow"                                },
		{ BlockType::Stone,                           "stone"                               },
		{ BlockType::StoneBricks,                     "stone bricks"                        },
		{ BlockType::SpruceLog,                       "spruce log"                          },
		{ BlockType::SprucePlanks,                    "spruce planks"                       },
		{ BlockType::Tnt,                             "tnt"                                 },
		{ BlockType::TubeCoral,                       "tube coral"                          },
		{ BlockType::WhiteConcrete,                   "white concrete"                      },
		{ BlockType::WhiteConcretePowder,             "white concrete powder"               },
		{ BlockType::WhiteWool,                       "white wool"                          },
		{ BlockType::Water,                           "water"                               },
		{ BlockType::YellowConcrete,                  "yellow concrete"                     },
		{ BlockType::YellowConcretePowder,            "yellow concrete powder"              },
		{ BlockType::YellowWool,                      "yellow wool"                         },
		{ BlockType::None,                            "none"                                }
	};
}